var row1 = document.getElementById("row1")
var row2 = document.getElementById("row2")
var row2 = document.getElementById("row3")
var row2 = document.getElementById("row4")
var row2 = document.getElementById("row5")
var row2 = document.getElementById("row6")
var row2 = document.getElementById("row7")
var row2 = document.getElementById("row8")
